sudo: false
branches:
  only:
  - pelican
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_f8d5cbc502db_key -iv $encrypted_f8d5cbc502db_iv -in publish-key.enc -out ~/.ssh/publish-key -d
- chmod u=rw,og= ~/.ssh/publish-key
- echo "Host github.com" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
- git remote set-url origin git@github.com:rschalch/rschalch.github.io.git
# Caso esteja montando a página de projeto troque master:master por gh-pages:gh-pages
- git fetch origin -f master:master
install:
- pip install --upgrade pip
- pip install -r requirements.txt
script:
- make github
